"""empty message

Revision ID: 4ed06ecee594
Revises: add_cards_table_001
Create Date: 2025-12-20 00:40:27.063609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ed06ecee594'
down_revision = 'add_cards_table_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['uploader_id'], ['id'])

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('topic_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
       # batch_op.drop_index(batch_op.f('ix_cards_order_index'))
        batch_op.create_index(batch_op.f('ix_cards_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_published'), ['published'], unique=False)
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'])
        batch_op.create_foreign_key(None, 'lessons', ['lesson_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_published'), ['published'], unique=False)

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_level'), ['level'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('target')
        batch_op.drop_column('scheduled_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_progress_attempt_id'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.CHAR(length=6),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('syllabus',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('class',
               existing_type=mysql.CHAR(length=4),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('courses',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('second_language',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('third_language',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'inactive'),
               nullable=False)
        batch_op.drop_index(batch_op.f('id'))
        batch_op.drop_index(batch_op.f('unique_students_email'))
        batch_op.create_index(batch_op.f('ix_students_email'), ['email'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_email'))
        batch_op.create_index(batch_op.f('unique_students_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('id'), ['id'], unique=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'inactive'),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('third_language',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('second_language',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('courses',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('class',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=4),
               nullable=False)
        batch_op.alter_column('syllabus',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(length=6),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_progress_attempt_id'), ['attempt_id'], unique=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('scheduled_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('target', mysql.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_column('data')
        batch_op.drop_column('body')
        batch_op.drop_column('user_id')
        batch_op.drop_column('is_read')
        batch_op.drop_column('icon')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_level'))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_published'))

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cards_published'))
        batch_op.drop_index(batch_op.f('ix_cards_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_cards_display_order'))
       # batch_op.create_index(batch_op.f('ix_cards_order_index'), ['display_order'], unique=False)
       # batch_op.create_index('ix_cards_display_order', ['display_order'], unique=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('topic_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
