#!/usr/bin/env python3
"""List all registered Flask routes as JSON.

This inspects the live Flask app instead of scraping source files, so it
includes routes from every blueprint (including `/api/v1` and others).
"""

import json
import os

from app import create_app


def main():
    base_url = os.environ.get("BASE_URL", "http://127.0.0.1:5000")
    app = create_app()

    routes = []
    with app.app_context():
        for rule in sorted(app.url_map.iter_rules(), key=lambda r: r.rule):
            methods = sorted(m for m in rule.methods if m not in {"HEAD", "OPTIONS"})
            if not methods:
                continue
            # Skip the static endpoint generated by Flask
            if rule.endpoint == "static" or rule.rule.startswith("/static"):
                continue
            routes.append({
                "rule": rule.rule,
                "methods": methods,
                "endpoint": rule.endpoint,
                "full_url": f"{base_url}{rule.rule}",
            })

    print(json.dumps(routes, indent=2))


if __name__ == "__main__":
    main()
